#!/usr/bin/env groovy
@Library('apm@current') _

pipeline {
  agent { label 'linux && immutable' }
  environment {
    BASE_DIR = 'src/github.com/elastic/apm-integration-testing'
    PIPELINE_LOG_LEVEL='INFO'
  }
  stages{
    stage('Checkout'){
      options { skipDefaultCheckout() }
      steps {
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}",
                    reference: '/var/lib/jenkins/.git-references/apm-integration-testing.git')
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    stage('Tests'){
      options { skipDefaultCheckout() }
      steps {
        deleteDir()
        unstash 'source'
        dir("${BASE_DIR}"){
          preCommit(commit: "${env.GIT_BASE_COMMIT}", junit: true)
        }
      }
    }
  }
}
